name: Unit

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 21 ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout Java Client
        uses: actions/checkout@v5

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Unit Test
        run: ./gradlew clean unitTest

      - name: Upload Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-java${{ matrix.java }}-${{ runner.os }}
          path: java-client/build/reports/
          retention-days: 7
  
  test-java8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-13]
    steps:
      - name: Checkout Java Client
        uses: actions/checkout@v5

      - name: Set up JDK 8 (Runtime)
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: gradle

      - name: Set up JDK 21 (Tools)
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Run Unit Test
        run: ./gradlew clean unitTest -D"runtime.java=8"

      - name: Upload Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-java8-${{ runner.os }}
          path: java-client/build/reports/
          retention-days: 7