name: Integration with Released OpenSearch

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { opensearch_version: 1.0.1, java: 11 }
          - { opensearch_version: 1.1.0, java: 11 }
          - { opensearch_version: 1.2.4, java: 11 }
          - { opensearch_version: 1.3.13, java: 11 }
          - { opensearch_version: 2.0.1, java: 11 }
          - { opensearch_version: 2.1.0, java: 11 }
          - { opensearch_version: 2.2.1, java: 11 }
          - { opensearch_version: 2.3.0, java: 11 }
          - { opensearch_version: 2.4.1, java: 11 }
          - { opensearch_version: 2.5.0, java: 11 }
          - { opensearch_version: 2.6.0, java: 11 }
          - { opensearch_version: 2.7.0, java: 11 }
          - { opensearch_version: 2.8.0, java: 11 }
          - { opensearch_version: 2.9.0, java: 11 }
          - { opensearch_version: 2.10.0, java: 11 }
    steps:
      - name: Checkout Java Client
        uses: actions/checkout@v3
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.entry.java }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Docker
        run: |
          docker-compose --project-directory .ci/opensearch build --build-arg OPENSEARCH_VERSION=${{ matrix.entry.opensearch_version }}
          docker-compose --project-directory .ci/opensearch up -d
          sleep 60
      - name: Run Integration Test
        run: ./gradlew clean integrationTest

      - name: Upload Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: java-client/build/reports/
          retention-days: 7

      - name: Stop Docker
        run: |
          docker-compose --project-directory .ci/opensearch down